Tainted References browser test fails locally with Error: Element not found
wmde/wdio-wikibase pull request #17
Opened 2020-02-10 16:46 UTC by rosalieper

Tainted References browser test fails locally with Error: Element not located on page.

For a reason still unknown, element.$(...EDIT_BUTTON).waitForExist(); does not wait
replacing that with element.waitForExist(...EDIT_BUTTON ) actually does the expected waiting.

Note that this behaviour happens both with waitForExist() and waitForVisible()

Bug: T244589
Bug: T243817

2020-02-10 17:44 UTC, manicki approved these changes
I have failed to understand so far why what seems a different way to address the same element makes a difference, but if this makes things work - the change makes sense.

Swapping `waitForExist` to `waitForVisible` makes sense to me.

I'd appreciate if someone more experience with wdio magic chimed in here.

2020-02-11 10:32 UTC, mariushoch approved these changes
Seems sensible, but I don't know enough about this to definitely merge.

2020-02-11 11:39 UTC, jakobw approved these changes
I ran `extensions/Wikibase/repo/tests/selenium/specs/tainted-ref.js` with and without this patch. Both worked fine. The change to `waitForVisible` makes sense to me.

I tried to figure out what the difference might be between `element.waitForVisible( selector )` and `element.$( selector ).waitForVisible()` but without much luck. Prior to wdio 5 it's really not well documented what the `$` or `element` method really returns. "A WebElement JSON object for the located element.
" - from the wdio [4.13 docs](http://v4.webdriver.io/api/protocol/element.html)

2020-02-11 11:56 UTC, lucaswerkmeister requested changes
> Swapping `waitForExist` to `waitForVisible` makes sense to me.

I find this part extremely confusing. The commit message explicitly says that it doesn’t make a difference, so why change it? Is it necessary after all?

*If* it makes sense to use the other method, but it’s independent of fixing the browser tests, then I think it should be in a separate commit.

2020-02-11 12:15 UTC, tzhelyazkova reviewed
Apparently they renamed `waitForVisible` to `waitForDisplayed`- https://github.com/webdriverio/webdriverio/blob/1b11d192fa30cd92724a21e3febbf40b9e5b3ba2/CHANGELOG.md
We should probably stick to `waitForExist` at least until we update the version of `wdio`.
This is also interesting - https://github.com/webdriverio/webdriverio/issues/3839

2020-02-11 14:58 UTC, tzhelyazkova approved these changes

2020-02-11 15:02 UTC, lucaswerkmeister approved these changes

2020-02-11 16:45 UTC, tarrow commented
I'm not sure this does what we want but as yet I don't have a yes model.

Using this code and reducing the wait time by adding an extra parameter to the waitForExist method (i.e. `element.waitForExist( this.constructor.TOOLBAR_WIDGET_SELECTORS.EDIT_BUTTON, 100 );`) resulted in the error:
`element (".wikibase-toolbar-button-edit") still not existing after 100ms`

This makes me think that it doesn't correctly look for the child element but simply ignores the value of `element`.

2020-02-12 10:07 UTC, tarrow approved these changes
So it seems that this works for everyone locally but I'm not convinced any of use quite got to the bottom of why it works.

The WDIO docs [1] don't seem to mention using waitForExist as a method on 'A WebElement JSON object' in combination with a selector.

There is evidence[2] of this syntax being used in one test that is expected to fail.

[1] http://v4.webdriver.io/api/utility/waitForExist.html
[2] https://github.com/webdriverio/webdriverio/blob/21766775de09fac492cff2385c809cbd17c655b0/test/fixtures/specs/waitfor.spec.js#L67

2020-02-12 10:23 UTC, merged