selenium: Remove webdriverio npm package
wmde/wdio-wikibase pull request #49
Opened 2023-01-23 23:54 UTC by vaughnwalters

selenium: Remove webdriverio npm package

The `webdriverio` package does not need to be an explicit dependency. It is a dependency of `@wdio/cli`.

Bug: https://phabricator.wikimedia.org/T325059

2023-01-24 12:12 UTC, zeljkofilipin requested changes
Please revert the change to lockfileVersion.

2023-01-24 12:12 UTC, zeljkofilipin commented on package-lock.json
> -	"lockfileVersion": 2,
You probably changed the lockfileVersion by mistake.

2023-01-24 20:13 UTC, vaughnwalters commented on package-lock.json
> -	"lockfileVersion": 2,
Yes you are correct, I have reverted this now @zeljkofilipin

2023-01-27 14:09 UTC, zeljkofilipin commented
To make sure this didn't break anything, we have to run Wikibase, WikibaseLexeme and wikibase-termbox test suites with this change.

2023-02-14 18:25 UTC, closed without merging