Compatibility with WDIO v8
wmde/wdio-wikibase pull request #72
Opened 2023-10-17 14:07 UTC by RickiJay-WMDE

- Per WDIO documentation, `browser.config` replaced by `browser.options`. To ensure compatibility with both, combined the two possible objects into one `config` object.
- Per experience, custom properties such as `mwUser` and `mwPwd` are no longer allowed. Established optional parameters to the `initialize()` method for `mwUser` and `mwPwd`.
- Updated dependencies

2023-10-18 10:07 UTC, RickiJay-WMDE commented
@jakobw @Silvan-WMDE @MuhammadJaziraly 
Apologies, I don't seem to have permission to request reviews in this repo, but I saw the three of you were the reviewers tagged for the last accepted PR. Please give this a look when you get a chance!

2023-10-23 12:40 UTC, andrewtavis-wmde commented
Assuming this review request was for the other Andrew? I'm seeing two other Andrew accounts in the organization, so not sure which one is the correct one to ping :)

2023-10-23 12:47 UTC, micgro42 commented
I think team WPP is the right team for this indeed. It has been well over 1.5 years since I last contributed here. Feel free to add me as a reviewer here again or ping me, if my input is needed in particular.

2023-10-23 13:05 UTC, RickiJay-WMDE commented
@micgro42 Thank you! Is there anyone in particular on WPP I should tag?

2023-10-23 13:41 UTC, micgro42 commented
> @micgro42 Thank you! Is there anyone in particular on WPP I should tag?

I think you already got the entire team there, so you should be good :). If there is a "WPP <-> Wikibase Suite collaboration" channel on Mattermost, then that might also be a good place to raise it. @manicki would know specifics.

2023-10-25 15:43 UTC, jakobw requested changes
Hi @RickiJay-WMDE, apologies for the late response. Thanks for the PR! I left some comments inline, but the backwards compatibility code looks good to me! :sparkles: 

I tried using this version of `wdio-wikibase` for the Wikibase browser test suite (installed via `npm i --save-dev wdio-wikibase@RickiJay-WMDE/wdio-wikibase#master`). It works ([patch](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Wikibase/+/968646)), but something doesn't seem quite right about all the dependencies that it's pulling in. That might be due to the legacy lock file format, but I'm not sure.

2023-10-25 15:43 UTC, jakobw commented on package.json
> +		"webdriverio": "^8.16"
Updating this peer dependency to just `^8.16` indicates that the package no longer supports v7 which would require a major version bump of `wdio-wikibase`. We allow both by doing the following:

```suggestion
		"webdriverio": "^7.0 || ^8.16"
```

2023-10-25 15:43 UTC, jakobw commented on package.json
> +		"eslint-config-wikimedia": "^0.25.1",
Nitpick: Keeping npm dependencies up to date is of course a good thing to do in general, but these don't have much to do with the rest of the PR.

2023-10-25 15:43 UTC, jakobw commented on package-lock.json
It looks like there's quite a huge diff here because you're using an older version of npm (`lockfileVersion` changed from 2 to 1). We usually try to avoid this by using similar (ideally the same) node and npm versions across the team(s). The WPP devs use [fresh](https://github.com/wikimedia/fresh) locally for any MediaWiki/Wikibase related node.js work.

2023-10-30 09:33 UTC, RickiJay-WMDE commented on package.json
> +		"webdriverio": "^8.16"
Makes absolute sense, thank you!

2023-10-30 09:33 UTC, RickiJay-WMDE commented on package-lock.json
Ah, thank you for explaining about fresh - I've updated accordingly

2023-10-30 09:34 UTC, RickiJay-WMDE commented on package.json
> +		"eslint-config-wikimedia": "^0.25.1",
Seems reasonable, I'll leave that to y'all. Reverted these changes.

2023-10-30 13:28 UTC, jakobw approved these changes
LGTM! :rocket:

2023-10-30 13:30 UTC, merged